source "https://rubygems.org"

gem "sinatra"
gem "json"
gem "thin"
gem "toy_robot", git: "https://github.com/bentheax/toy_robot.git"
gem "rake"
gem "rspec"
gem "rack-test"
gem "json_expressions"
gem "simplecov"
gem "codeclimate-test-reporter", "~> 1.0.0"
